### ISSUE TITLE
Is it possible to support indent-based grammars?

### ISSUE THREAD

**Issue by singalen** [seanyoung/lrpeg#1]
Pest, on top of PEG, has a [stack support](https://pest.rs/book/grammars/syntax.html), and through it [it can support an indent levels](https://github.com/pest-parser/pest/issues/328).
Is it somehow possible in lrpeg?

**Comment by seanyoung** [comment]
Since lrpeg does not process whitespace in a special way, this is straightforward. I've given an example in #2 

Please let me know if this helps
