### ISSUE TITLE
ambiguous tokens

### ISSUE THREAD

**Issue by advancedtw** [seanyoung/lrpeg#3]
since the operator "~" doesn't seem to be supported and the regex crate can't do look-ahead operations what is the best way to disambiguate between identifiers and keywordsI have tried to reorder them but it's not ideal because it will either fail to parse or end up in the wrong branch.

also thank you for making lrpeg available!

**Comment by seanyoung** [comment]
Hi @advancedtw 
You can use the alternative feature of pegs:
```
word <- "while" / "for" / XID_IDENTIFIER;
```
Can you share a bit more the language/grammar you trying to match?

**Comment by advancedtw** [comment]
yes I'm writing a peg grammar for [cel](https://github.com/google/cel-spec/blob/master/doc/langdef.md) I've included the relevant part. 
the important rule is "primary" if I try to match "TRUE" it will match identifier instead of literal. 
if I switch the order then something like "TRUE_" or "form" will fail to parse.  
btw would like to use "true" instead of "TRUE" but I get a conflict with rust reserved keywords.

one other thing, in the generated code below is this a typo?
```
 match ch {
            '\\' => res.push_str("\\\\"),
            '\t' => res.push_str("\\t"),
            '\n' => res.push_str("\\n"),
            '\r' => res.push_str("\\t"),  // is it supposed to be \\r ?
            '"' => res.push_str("\\\""),
            ch => res.push(ch),
        }
```

peg grammar for cel (missing strings and bytes) 
```
start <- ws expr ws EOI;

expr <-   conditionalOr ("?" ws conditionalOr  ":" ws expr)?;

conditionalOr <- conditionalAnd ("||" ws conditionalAnd)*;

conditionalAnd <- relation ("&&" ws relation)*;

relation
    <- relation  ("<="/"<"/">="/">"/"=="/"!="/"IN") ws relation
    / calc
    ;

calc
    <- calc  ("*"/"/"/"%")  ws calc 
    / calc  ("+"/"-")  ws calc
    / unary
    ;

unary
    <- ws  "!"+ ws member                                            
    /  ws "-"+  ws member   
    /  member                                         
    ;

member
    <- member "." identifier ("(" exprList? ")")?
    / member "[" expr "]"                                 
    / member "{" ws fieldInitializerList? ","?  ws "}"      
    / primary       
    ;

primary
    <- 
    "."? identifier ("(" exprList? ")")?                      
    / "("  expr  ")"                                               
    / "[" exprList? ","? "]"                              
    / "{" ws mapInitializerList? ","?  ws "}"       
    /  literal           
                                      
    ;

exprList
    <- expr ("," expr)*
    ;

fieldInitializerList
    <- identifier ":" ws expr ("," ws identifier ":" ws expr)*
    ;

mapInitializerList
    <- expr ws ":" ws expr ("," ws expr  ws ":" ws  expr)*
    ;

literal
    <- "-"? ws num_float ws
    / num_uint ws
    / "-"? ws num_int ws
    / bytes ws
    / strings ws
    / "TRUE" ws
    / "FALSE" ws
    / "NULL" ws
    ;


digit <- re#[[:digit:]]#;
identifier <- re#[a-zA-Z_][a-zA-Z0-9_]*# ws;
exponent <- re#[eE][\+-]?[[:digit:]]#;
num_int <-  re#0x[[:hexdigit:]]+|[[:digit:]]+#;
num_uint <-  re#0x[[:hexdigit:]]+[uU]|[[:digit:]]+[uU]#;

num_float <- (digit+ ("." digit+) exponent?
                    / digit+ exponent
                    / "." digit+ exponent?);

ws <-  WHITESPACE re#(?://.*\n?)+# ws
    / WHITESPACE;

```

**Comment by seanyoung** [comment]
Thanks for pointing out the typo in `'\r' => res.push_str("\\t"),`, I've correct this

**Comment by seanyoung** [comment]
In the rule `primary` you must have "TRUE" and "FALSE" as an alternative before identifier, else identifier will patch true/false.

Also for the || and &&, I would do:

```
conditionalOr <- conditionalOr "||" ws conditionalOr
         / conditionalAnd;

conditionalAnd <- conditionalAnd "&&" ws conditionalAnd
         / relational;
```

**Comment by advancedtw** [comment]
thank you for the feedback I will try to update the grammar with your recommendations.
I will play again with the order of rules until I can find something that works. 

> btw would like to use "true" instead of "TRUE" but I get a conflict with rust reserved keywords.

currently I'm using re#\btrue\b# instead of "true" because lrpeg will generate Terminal::true and conflict with rust. 
if the terminal variants were delimited with  "__"  ex: "\__true __" that may help.

**Comment by seanyoung** [comment]
I've just pushed a change that should deal with the rust keyword issue.

**Comment by advancedtw** [comment]
thank you very much for fixing the keyword conflict. 
since all the problems have been addressed I think it's safe to close the issue.
